### ISSUE TITLE
Sounds not muffled at all

### ISSUE THREAD

**Issue by moro96messier** [SebaSOFT/walls-have-ears#36]
I've placed a sound behind a wall, set sound restriction to none and there is no muffle. Any chance that I'm doing something wrong?

**Comment by SebaSOFT** [comment]
This usually happens when:

- Disabled Token Vision on the scene (this is a MUST)
- Disabled "Constrained by Walls" on the Sound
- Set sound occlussion on Walls to other than none

Hearing the muffling can vary from sound to sound when  the sound has lots of high or low pitch. This is because the high pass filter will filter out nothing. Try it with different sounds.
